services:
    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
        ports: ["5432:5432"]
        volumes: [pgdata:/var/lib/postgresql/data]
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U app -d app"]
            interval: 10s
            timeout: 5s
            retries: 10

    redis:
        image: redis:7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        ports: ["6379:6379"]

    meilisearch:
        image: getmeili/meilisearch:v1.10
        environment:
            MEILI_ENV: development
            MEILI_NO_ANALYTICS: "true"
            MEILI_MASTER_KEY: masterKey
        ports: ["7700:7700"]
        volumes: [meili:/meili_data]
        healthcheck:
            test: ["CMD", "wget", "--spider", "-q", "http://localhost:7700/health"]
            interval: 10s
            timeout: 5s
            retries: 10

volumes:
    pgdata:
    meili:
